spring:
  application:
    name: voucher-api
  server:
    port: 80
  datasource:
    url: jdbc:h2:mem:voucher-db
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
